CREATE DATABASE genube_desafio_tecnico;

CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(200) NOT NULL,
password VARCHAR(500) NOT NULL,
deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE roles(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
description VARCHAR(500),
deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE assigned_roles(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT,
role_id INT,
is_assigned TINYINT(1) NOT NULL DEFAULT 1,
create_date DATETIME NOT NULL,

FOREIGN KEY (user_id)REFERENCES users(id),
FOREIGN KEY (role_id)REFERENCES roles(id)
);
